name: flutter_starter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Media
  image_picker: ^1.1.2

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.5.1
  
  # Navigation
  go_router: ^14.2.0
  
  # Authentication
  supabase_flutter: ^2.5.0
  
  # UI/UX
  flutter_animate: ^4.5.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.0
  file_picker: ^8.0.0
  
  # Storage
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.2.0
  
  # Networking
  dio: ^5.5.0
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.5.1

flutter:
  uses-material-design: true
  generate: true
